backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  media_folder: "images/"

  # Please run "npx netlify-cms-proxy-server" for local backend
  local_backend: true

  publish_mode: editorial_workflow