backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: /images/
media_library:
  name: cloudinary
  config:
    cloud_name: bpc-cloud
    api_key: 887479154912573
public_folder: /images/
collections:
  - name: "home"
    label: "Home"
    folder: "data/"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slogan", name: "siteSlogan", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Phone Number", name: "companyPhoneNumber", widget: "string"}
      - {label: "Mission Statement", name: "companyMissionStatement", widget: "string"}
      - label: "FAQ" 
        name: "faq" 
        widget: "list"
        allow_add: true
        fields: 
          - {label: "First Question", name: "faqFirstQuestion", widget: "string"}
          - {label: "First Answer", name: "faqFirstAnswer", widget: "string"}