backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: /images/
media_library:
  name: cloudinary
  config:
    name: bpc-cloud
    publicKey: 887479154912573
public_folder: /images/
collections:
  - name: "home"
    label: "Home"
    folder: "data/"
    fields:
      - {label: "Title", name: "title", widget: "string"}